//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentCar.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class rentcarEntities : DbContext
    {
        public rentcarEntities()
            : base("name=rentcarEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cliente> Clientes { get; set; }
        public virtual DbSet<Empleado> Empleados { get; set; }
        public virtual DbSet<Inspeccione> Inspecciones { get; set; }
        public virtual DbSet<Marca> Marcas { get; set; }
        public virtual DbSet<Modelo> Modelos { get; set; }
        public virtual DbSet<Renta_Devolucion> Renta_Devolucion { get; set; }
        public virtual DbSet<Tipos_Combustibles> Tipos_Combustibles { get; set; }
        public virtual DbSet<Tipos_Vehiculos> Tipos_Vehiculos { get; set; }
        public virtual DbSet<Vehiculo> Vehiculos { get; set; }
    }
}
