//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentCar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inspeccione
    {
        public int Id_Transaccion { get; set; }
        public int Vehiculo { get; set; }
        public int Id_Cliente { get; set; }
        public string Tiene_Ralladuras { get; set; }
        public string Cantidad_Combustible { get; set; }
        public string Tiene_Goma_respuesta { get; set; }
        public string Tiene_Gato { get; set; }
        public string Tiene_Roturas_Cristal { get; set; }
        public string Estado_GomaA { get; set; }
        public string Estado_GomaB { get; set; }
        public string Estado_GomaC { get; set; }
        public string Estado_GomaD { get; set; }
        public System.DateTime Fecha { get; set; }
        public int Empleado_Inspeccion { get; set; }
        public string Estado { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Empleado Empleado { get; set; }
        public virtual Vehiculo Vehiculo1 { get; set; }
    }
}
