//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentCar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Renta_Devolucion
    {
        public int No_Renta { get; set; }
        public int Empleado { get; set; }
        public int Vehiculo { get; set; }
        public int Cliente { get; set; }
        public System.DateTime Fecha_Renta { get; set; }
        public System.DateTime Fecha_Devolucion { get; set; }
        public int MontoxDia { get; set; }
        public int Cantidad_Dias { get; set; }
        public string Comentario { get; set; }
        public string Estado { get; set; }
    
        public virtual Cliente Cliente1 { get; set; }
        public virtual Empleado Empleado1 { get; set; }
        public virtual Vehiculo Vehiculo1 { get; set; }
    }
}
