//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentCar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehiculo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vehiculo()
        {
            this.Inspecciones = new HashSet<Inspeccione>();
            this.Renta_Devolucion = new HashSet<Renta_Devolucion>();
        }
    
        public int Id_Vehiculo { get; set; }
        public string Descripcion { get; set; }
        public string No_Chasis { get; set; }
        public string No_Motor { get; set; }
        public string No_Placa { get; set; }
        public int Tipo_Vehiculo { get; set; }
        public int Marca { get; set; }
        public int Modelo { get; set; }
        public int Tipo_Combustible { get; set; }
        public string Estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inspeccione> Inspecciones { get; set; }
        public virtual Marca Marca1 { get; set; }
        public virtual Modelo Modelo1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Renta_Devolucion> Renta_Devolucion { get; set; }
        public virtual Tipos_Combustibles Tipos_Combustibles { get; set; }
        public virtual Tipos_Vehiculos Tipos_Vehiculos { get; set; }
    }
}
